### ISSUE TITLE
Deprecated REST API

### ISSUE THREAD

**Issue by ptheuwis** [JetBrains/YouTrackSharp#105]
As received by email from YouTrack, the REST API will be depreciated as of july 2021. "In the upcoming 2021.3 release, support for this version of the API will be discontinued. This means that its endpoints will be deactivated to ignore incoming requests."
https://www.jetbrains.com/help/youtrack/incloud/2021.2/monitor-rest-api-traffic.html

Will this library being updated?

Thanks.

**Comment by maartenba** [comment]
Hi @ptheuwis - check https://blog.jetbrains.com/youtrack/2021/02/discontinuing-the-legacy-rest-api-action-required/#remark42__comment-cff1dd5e-b0bf-4372-809f-80e6e1db6066 for the discussion around this topic.

**Comment by ptheuwis** [comment]
Thank you for the response! If I understand correctly, there will be a new version launched of YouTrackSharp. Is this new version launched before July 1st?

**Comment by SteveHaine** [comment]
I have made a start on this for some work I needed (mainly relating to IssueWorkItem & Time Tracking) on my fork https://github.com/SteveHaine/YouTrackSharp.

**Comment by Eb0nheart** [comment]
@maartenba Are there any updates on the progress of the package update? I cant seem to find what the expected release of it is and i don't know whether to wait or start refactor our code to use the AuthenticatedHttpClient to use the new API instead.

**Comment by jk1** [comment]
@SteveHaine @Eb0nheart @ptheuwis  we are working on the new YouTrackSharp version right now. The current plan is to make it available before July 1st. We'll start disabling the deprecated API in the cloud no earlier than July 13th, so you should have a bit of a breathing space there. 

Please note, that it's likely to be the binary incompatible change, so some work may be required on your side as well.

**Comment by ptheuwis** [comment]
Good news @jk1 ! Thank you.

**Comment by rekolobov** [comment]
Dear all,
Please accept my deepest apologies for the delay with release publication and lack of communication.

2021.3.0 has been made [available for download](https://www.nuget.org/packages/YouTrackSharp/2021.3.0)

Please carefully inspect [release notes](https://github.com/JetBrains/YouTrackSharp/releases/tag/2021.3.0) -- they should assist you in migrating your code.
We have tried to keep API changes to the minimum, but still intentionally broke compatibility in a few places to avoid obvious runtime errors.

Should any problems arise or should you not have enough time to migrate your instance (which is understandable), please contact us here or in support.
We'll try to fix any bugs caused by migration ASAP, should you post any.

**Comment by kolibaba** [comment]
Do I understand correctly that the new version of YouTrackSharp cannot be used in our project, because it uses .net 4.8?
