### ISSUE TITLE
Package YouTrackSharp 2021.3.1 is not compatible with net48

### ISSUE THREAD

**Issue by kolibaba** [JetBrains/YouTrackSharp#109]
## Expected behavior
The ability to use the library

## Actual behavior
Can't add ref to lib

## Steps to reproduce the behavior
Trying install by Nuget console

**Comment by rekolobov** [comment]
we're expecting to release compatible build today

**Comment by kolibaba** [comment]
When to expect a new release?

**Comment by kolibaba** [comment]
Tried version 2021.3.2.0 from git - works fine in my project . Waiting for publication in Nuget

**Comment by rekolobov** [comment]
yup, apologies for delays, I've been trying to get packaging straight since Friday -- somehow we get issues with references to system libraries for target 4.8 (no other issues though), hope to resolve today

otherwise I'll just package a prerelease build and release a proper build tomorrow or on Wednesday

**Comment by rekolobov** [comment]
2021.3.2 has finally been published to NuGet, please ping us back if you find any issues with library references
